spring:
  application:
    name: web02
  #数据库的连接信息
  datasource:
    url: jdbc:mysql://localhost:3306/db02
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 7017606

#Mybatis的相关配置
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/*.xml